CompileFlags:
  Add:
    - -std=c++14  # Use C++14 standard; adjust if needed
    - -I/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include  # NDK headers
    - -I/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/x86_64-linux-android/asm  # Android platform headers
    - -I/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aarch64-linux-android/asm  # Android platform headers
    - -I/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/arm-linux-androideabi/asm  # Android platform headers
    - -I/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/i686-linux-android/asm  # Android platform headers
    - -I/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/riscv64-linux-android/asm  # Android platform headers
    - -I/usr/include
    # - -I/path/to/your/project/include  # Your project include directory
    - -DANDROID  # Define for Android
    - -fexceptions  # Enable exception handling
    - -funwind-tables  # Enable stack unwinding
    - -frtti  # Enable run-time type information
  Remove:
    - -W*  # Remove all warning flags if needed

CompilationDatabase:
  Ancestors: true  # Look for compile_commands.json in parent directories

Index:
  Background: Build  # Enable background indexing

Diagnostics:
  ClangTidy:
    Add:
      - modernize-*  # Enable all modernize checks
    Remove:
      - modernize-use-trailing-return-type  # Exclude a specific check

InlayHints:
  Enabled: true
  ParameterNames: true
  DeducedTypes: true

# Optional: Customize the indexing behavior
Index:
  StandardLibrary: No  # Disable eager indexing of the standard library

# Optional: Configure unused includes diagnostics
Diagnostics:
  UnusedIncludes: Strict  # Enable strict checks for unused includes
